process.env.AZURE_STORAGE_CONNECTION_STRING = 'connection-string'
process.env.AZURE_STORAGE_ACCOUNT_NAME = 'storage-account'
process.env.MESSAGE_QUEUE_HOST = 'host'
process.env.MESSAGE_QUEUE_PASSWORD = 'password'
process.env.MESSAGE_QUEUE_USER = 'user'
process.env.APPLICATIONPAYMENTREQUEST_QUEUE_ADDRESS = 'queue-address'
process.env.PAYMENTREQUEST_TOPIC_ADDRESS = 'topic-address'
process.env.PAYMENTRESPONSE_TOPIC_ADDRESS = 'topic-address'
