services:
  ffc-ahwr-payment:
    build:
      context: .
      target: production
    image: ffc-ahwr-payment
    container_name: ffc-ahwr-payment
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-payment-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
