services:
  ffc-ahwr-payment:
    build:
      context: .
      target: production
    image: ffc-ahwr-payment
    container_name: ffc-ahwr-payment
    depends_on:
      - ffc-ahwr-payment-postgres
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ahwr-payment-local
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      APPLICATIONPAYMENTREQUEST_QUEUE_ADDRESS: ${APPLICATIONPAYMENTREQUEST_QUEUE_ADDRESS:-ffc-ahwr-payment-request}${MESSAGE_QUEUE_SUFFIX}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}
      PAYMENTREQUEST_TOPIC_ADDRESS: ${PAYMENTREQUEST_TOPIC_ADDRESS:-ffc-pay-request}${MESSAGE_QUEUE_SUFFIX}
      PAYMENTRESPONSE_TOPIC_ADDRESS: ${PAYMENTRESPONSE_TOPIC_ADDRESS:-ffc-pay-request-response}${MESSAGE_QUEUE_SUFFIX}
      PAYMENTRESPONSE_SUBSCRIPTION_ADDRESS: ${PAYMENTRESPONSE_SUBSCRIPTION_ADDRESS:-ffc-ahwr-application}
      POSTGRES_DB: ffc_ahwr_payment
      POSTGRES_HOST: ${POSTGRES_HOST:-ffc-ahwr-payment-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      SEND_PAYMENT_REQUEST: ${SEND_PAYMENT_REQUEST:-true}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-changeme}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      AZURE_STORAGE_ACCOUNT_NAME: ${AZURE_STORAGE_ACCOUNT_NAME:-changeme}
      PAYMENT_DATA_REQUEST_TOPIC_ADDRESS: ${PAYMENT_DATA_REQUEST_TOPIC_ADDRESS:-ffc-pay-data-request}
      PAYMENT_DATA_REQUEST_RESPONSE_ADDRESS: ${PAYMENT_DATA_REQUEST_RESPONSE_ADDRESS:-ffc-pay-data-request-response}
      PAYMENT_MESSAGE_QUEUE_HOST: ${PAYMENT_MESSAGE_QUEUE_HOST:-notset}
      PAYMENT_MESSAGE_QUEUE_USER: ${PAYMENT_MESSAGE_QUEUE_USER:-notset}
      PAYMENT_MESSAGE_QUEUE_PASSWORD: ${PAYMENT_MESSAGE_QUEUE_PASSWORD:-notset}
      PAYMENT_AZURE_STORAGE_CONNECTION_STRING: ${PAYMENT_AZURE_STORAGE_CONNECTION_STRING:-changeme}
      PROCESS_PAYMENT_DATA_SCHEDULER_ENABLED: ${PROCESS_PAYMENT_DATA_SCHEDULER_ENABLED:-true}
      PROCESS_PAYMENT_DATA_SCHEDULE: ${PROCESS_PAYMENT_DATA_SCHEDULER_CRON:-0 0 * * *}


  ffc-ahwr-payment-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_ahwr_payment
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}