# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-ahwr-payment:
    build:
      target: development
    image: ffc-ahwr-payment-development
    container_name: ffc-ahwr-payment-test
    command: npm run test
    environment:
      NODE_OPTIONS: "$NODE_OPTIONS --experimental-vm-modules"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./test-output:/home/node/test-output
      - ./jest.config.cjs:/home/node/jest.config.cjs
      - ./package.json:/home/node/package.json

  ffc-ahwr-payment-postgres:
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: