{{- include "ffc-helm-library.container-config-map" (list . "ffc-ahwr-payment.config-map") -}}
{{- define "ffc-ahwr-payment.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  APPLICATIONPAYMENTREQUEST_QUEUE_ADDRESS: {{ quote .Values.container.applicationPaymentRequestQueueAddress }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  PAYMENTREQUEST_TOPIC_ADDRESS: {{ quote .Values.container.paymentRequestTopicAddress }}
  PAYMENTRESPONSE_TOPIC_ADDRESS: {{ quote .Values.container.paymentResponseTopicAddress }}
  PAYMENTRESPONSE_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.paymentResponseSubscriptionAddress }}
  POSTGRES_DB: {{ quote .Values.postgresService.postgresDb }}
  POSTGRES_HOST: {{ quote .Values.postgresService.postgresqlHost }}
  POSTGRES_PORT: {{ quote .Values.postgresService.postgresPort }}
  POSTGRES_SCHEMA_NAME: {{ quote .Values.postgresService.postgresSchema }}
  SEND_PAYMENT_REQUEST: {{ quote .Values.container.sendPaymentRequest }}
  AZURE_STORAGE_USE_CONNECTION_STRING: {{ quote .Values.container.azureStorageUseConnectionString }}
  AZURE_STORAGE_ACCOUNT_NAME: {{ quote .Values.container.azureStorageAccountName }}
  AZURE_STORAGE_PAYMENT_DATA_HUB_CONNECTION_STRING: {{ quote .Values.container.azureStoragePaymentDataHubConnectionString }}
  AZURE_STORAGE_PAYMENT_DATA_HUB_DATA_REQUESTS_CONTAINER: {{ quote .Values.container.azureStoragePaymentDataHubDataRequestsContainer }}
  APPLICATION_REQUEST_QUEUE_ADDRESS: {{ quote .Values.container.applicationRequestQueueAddress }}
  PAYMENT_DATA_REQUEST_TOPIC_ADDRESS: {{ quote .Values.container.paymentDataRequestTopicAddress }}
  PAYMENT_DATA_REQUEST_RESPONSE_QUEUE_ADDRESS: {{ quote .Values.container.paymentDataRequestResponseQueueAddress }}
{{- end -}}
