{{- include "ffc-helm-library.container-secret" (list . "ffc-ahwr-payment.container-secret") -}}
{{- define "ffc-ahwr-payment.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  POSTGRES_USERNAME: {{ quote .Values.postgresService.postgresUser }}
{{- end -}}
