apiVersion: v2
description: FFC Vet Visits Payment Service
name: ffc-ahwr-payment
# this version is automatically updated in the build pipline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: 4.0.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
