environment: development
image: ffc-ahwr-payment
name: ffc-ahwr-payment
namespace: ffc-ahwr
workstream: ffc-ahwr

labels: {}

aadPodIdentity: true

azureIdentity:
  clientID:
  resourceID:

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-ahwr-payment-config-map

containerSecret:
  name: ffc-ahwr-payment-container-secret
  type: Opaque

deployment:
  cpuThreshold: 40
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 1
  maxReplicas: 1
  priorityClassName: default
  restartPolicy: Always
  replicas: 1

container:
  applicationPaymentRequestQueueAddress: ffc-ahwr-payment-request
  paymentRequestTopicAddress: ffc-pay-request
  paymentResponseTopicAddress: ffc-pay-request-response
  paymentResponseSubscriptionAddress: ffc-ahwr-application
  sendPaymentRequest: "true"
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 40Mi
  limitCpu: 40m
  port: 3000

postgresService:
  postgresDb: ffc_ahwr_payment
  postgresExternalName: namespace.postgres.database.azure.com
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
