environment: development
image: ffc-ahwr-payment
name: ffc-ahwr-payment
namespace: ffc-ahwr
workstream: ffc-ahwr

labels: {}

workloadIdentity: true

azureIdentity:
  clientID:
  resourceID:

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-ahwr-payment-config-map

containerSecret:
  name: ffc-ahwr-payment-container-secret
  type: Opaque

deployment:
  cpuThreshold: 40
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 1
  maxReplicas: 1
  priorityClassName: default
  restartPolicy: Always
  replicas: 1

container:
  applicationPaymentRequestQueueAddress: ffc-ahwr-payment-request
  messageQueueHost: namespace.servicebus.windows.net
  paymentRequestTopicAddress: ffc-pay-request
  paymentResponseTopicAddress: ffc-pay-request-response
  paymentResponseSubscriptionAddress: ffc-ahwr-application
  azureStorageConnectionString:
  azureStorageUseConnectionString: true
  azureStorageAccountName:
  azureStorageEndemicsSettingsContainerName:
  sendPaymentRequest: "true"
  applicationRequestQueueAddress:  ffc-ahwr-application-request
  paymentDataRequestTopicAddress: ffc-pay-data-request
  paymentDataRequestResponseQueueAddress: ffc-pay-data-request-response
  requestPaymentStatusEnabled: "false"
  requestPaymentStatusSchedule: 0 20 * * 1-5
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 120Mi
  limitCpu: 120m
  port: 3000

postgresService:
  postgresDb: ffc_ahwr_payment
  postgresqlHost: namespace.postgres.database.azure.com
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 120
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 120
  periodSeconds: 10
  failureThreshold: 3
